language: cpp
compiler: gcc
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
    - dpkg
    - git
    - wget
    - cmake
    - qt510base
    - libcurl4-openssl-dev
    - librsvg2-bin
    - libfuse-dev
    - desktop-file-utils

notifications:
  email: false


script:
  - . /opt/qt510/bin/qt510-env.sh
  - export QT_SELECT=qt5
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .
  - make
  - DESTDIR=AppDir make install
  - wget https://github.com/TheAssassin/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/TheAssassin/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - chmod +x linuxdeploy-x86_64.AppImage
  - chmod +x linuxdeploy-plugin-qt-x86_64.AppImage
  - find AppDir -type f -iname '*.so*' -exec strip '{}' \;
  - ./linuxdeploy-x86_64.AppImage --init-appdir --appdir=AppDir --plugin qt --output appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh AppImage*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
