language: cpp
compiler: gcc
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
    - dpkg
    - git
    - wget
    - cmake
    - libcurl4-openssl-dev
    - librsvg2-bin
    - libfuse-dev
    - qt510base
    - graphicsmagick
    - desktop-file-utils

notifications:
  email: false

script:
  - source /opt/qt*/bin/qt*-env.sh
  - export QT_SELECT=qt5
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .
  - make
  - DESTDIR=AppDir make install
  - cp -R AppDir linuxdeploy.AppDir
  - cp -R AppDir linuxdeployqt.AppDir
  - wget https://github.com/TheAssassin/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/TheAssassin/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - chmod +x linuxdeploy*-x86_64.AppImage
  - #find AppDir -type f -iname '*.so*' -print0 | xargs -0 -i -n1 sh -c 'echo {}; strip {}' \;
  - export NO_STRIP=1
  - ./linuxdeploy-x86_64.AppImage --init-appdir --appdir=linuxdeploy.AppDir --plugin qt --output appimage
  - mv AppImage_Metadata_Extractor*.AppImage AppImage_Metadata_Extractor.linuxdeploy.AppImage
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage linuxdeployqt.AppDir/usr/share/applications/*.desktop -bundle-non-qt-libs -no-strip
  - ./linuxdeployqt-continuous-x86_64.AppImage linuxdeployqt.AppDir/usr/share/applications/*.desktop -appimage -no-strip
  - mv AppImage_Metadata_Extractor-*x86_64.AppImage AppImage_Metadata_Extractor.linuxdeployqt.AppImage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh AppImage*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
