language: cpp
compiler: gcc
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - dpkg
    - wget
    - cmake
    - librsvg2-bin
    - libfuse-dev
    - desktop-file-utils
    - binutils-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libboost-program-options-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-dev

notifications:
  email: false

script:
  - find /usr/include/libxml2/
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .
  - make
  - DESTDIR=AppDir make install
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - chmod +x linuxdeploy*-x86_64.AppImage
  - #find AppDir -type f -iname '*.so*' -print0 | xargs -0 -i -n1 sh -c 'echo {}; strip {}' \;
  - export NO_STRIP=1
  - ./linuxdeploy-x86_64.AppImage --init-appdir --appdir=AppDir --output appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh AppImage*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
